### ISSUE TITLE
Routing not working with latest KiCad 7.0.7 release

### ISSUE THREAD

**Issue by adamws** [adamws/kicad-kbplacer#8]
:warning:  To anyone using release v0.5 with KiCad 7.0.7 - routing is not working due to KiCad's API change. Do not use `Route tracks` option. It does work with 7.0.6.

```
        for track in self.board.GetTracks():
>           if connectivity.TestTrackEndpointDangling(track):
E           TypeError: CONNECTIVITY_DATA.TestTrackEndpointDangling() missing 1 required positional argument: 'aIgnoreTracksInPads'
```
